In [2]:
[[123,12,123,12,33],[],[]]


[[123, 12, 123, 12, 33], [], []]

In [4]:
import numpy
n=numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [7]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [8]:
m=numpy.asarray([[123,12,123,12,33],[],[]])
m

array([list([123, 12, 123, 12, 33]), list([]), list([])], dtype=object)

In [41]:
import cv2
im_g=cv2.imread("small_gray.jpg", 0)
im_c=cv2.imread("small_gray.jpg", 1)
im_g


array([[189, 156,  92, 123, 155],
       [189, 127, 255, 255, 133],
       [218, 134, 255,  92, 187]], dtype=uint8)

In [17]:
cv2.imwrite("newsmallgray.png", im_g)

True

In [25]:
im_g[0:2,2:4]



array([[ 92, 123],
       [255, 255]], dtype=uint8)

In [28]:
for i in im_g.T:
    print(i)

[189 189 218]
[156 127 134]
[ 92 255 255]
[123 255  92]
[155 133 187]


In [31]:
for i in im_g.flat:
    print(i)

189
156
92
123
155
189
127
255
255
133
218
134
255
92
187


In [ ]:
ims=numpy.hstack((im_g,im_c, im_g))
ims

In [45]:
ims=numpy.hstack((im_g, im_g))

lst=numpy.vsplit(ims, 3)
lst

[array([[189, 156,  92, 123, 155, 189, 156,  92, 123, 155]], dtype=uint8),
 array([[189, 127, 255, 255, 133, 189, 127, 255, 255, 133]], dtype=uint8),
 array([[218, 134, 255,  92, 187, 218, 134, 255,  92, 187]], dtype=uint8)]